server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/rkrisanoff/soa-config
          clone-on-start: true
  security:
    user:
      name: test
      password: test
